steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image for training'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/train-image',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image for training'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/train-image'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image for api'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/api-image',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image for api'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/api-image'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image for frontend'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/frontend-image',
    '-f',
    'dockerfiles/frontend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image for frontend'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-447920/mlops-fruit-and-vegetables/frontend-image'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1