model_config:
  _target_: model.ResNetModel
  model_type: "resnet18"  # Options: "resnet18", "resnet34", "resnet50"
  input_channels: 3
  num_classes: 36          
  pretrained: true        
desired_input_resolution: [224, 224]