model_config:
  _target_: model.ResNetModel
  model_type: "resnet34"  # Options: "resnet18", "resnet34", "resnet50"
  input_channels: 1
  num_classes: 10          
  pretrained: true        
desired_input_resolution: [224, 224]