data_dir: data/raw/fruit_vegetable
input_channels: 3
labels:
- apple
- turnip
name: FruitVegetable
preprocess_class: FruitVegetableDataset
process_config:
  output_folder: data/processed/fruit_vegetable
  partial: true
  test_images_file: test_images.pt
  test_target_file: test_target.pt
  train_images_file: train_images.pt
  train_target_file: train_target.pt
  val_images_file: val_images.pt
  val_target_file: val_targets.pt
test_class: FruitVegetableTestDataset
train_class: FruitVegetableTrainDataset
val_class: FruitVegetableValDataset
