data_dir: data/raw/Fruit
input_channels: 3
labels:
- apple
- banana
name: Fruit
preprocess_class: FruitDataset
process_config:
  output_folder: data/processed/Fruit
  partial: true
  test_images_file: test_images.pt
  test_target_file: test_target.pt
  train_images_file: train_images.pt
  train_target_file: train_target.pt
  val_images_file: val_images.pt
  val_target_file: val_targets.pt
test_class: FruitTestDataset
train_class: FruitTrainDataset
val_class: FruitValDataset
