# mnist data configuration to specify the data path and other parameters
name: mnist
preprocess_class: MNISTDataset
train_class: MNISTTrainDataset
val_class: MNISTTestDataset
test_class: MNISTTestDataset
data_dir: data/raw/mnist
input_resolution: [28, 28]
input_channels: 1
process_config:
  output_folder: data/processed/mnist
  train_images_file: train_images.pt
  train_target_file: train_target.pt
  val_images_file: val_images.pt
  val_target_file: val_target.pt
  test_images_file: test_images.pt
  test_target_file: test_target.pt
  partial: False